# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Hello, Azure DevOps Pipeline!"
    echo "Pipeline running successfully."
  displayName: 'Run a script'

- script: |
    echo "Add tasks to build, test, and deploy your project."
    echo "Refer to https://aka.ms/yaml for more details."
  displayName: 'Run additional tasks'